release 4.1.9

diff --git a/airtools-cli b/airtools-cli
--- a/airtools-cli
+++ b/airtools-cli
@@ -19,8 +19,8 @@
 ########################################################################
 AOVARS="AO_SKIP AO_FLATS AO_LIGHT AO_BGVAR AO_REGIS AO_STACK AO_AMASK AO_ACOOR AO_ABINN"
 
-VERSION="1.3.8"
-VINFO="T. Lehmann, Mar. 2022"
+VERSION="1.3.9"
+VINFO="T. Lehmann, Apr. 2022"
 PINFO="\
     options:
       -h            show this help text
@@ -34,6 +34,10 @@ PINFO="\
       task          run given task    
 "
 CHANGELOG="
+    1.3.9 - 26 Apr 2022
+        * imageinfo: rework to allow multiple entries in AO_SKIP
+        * reduce output messages if option quiet is set
+
     1.3.8 - 31 Mar 2022
         * stack: lower threshold for detecting sources from 5 to 3.5
 
@@ -475,16 +479,22 @@ _imageinfo () {
     local tel
     local tellist
     local f
-    local skippat=".__."
+    local extargs
+    local skipargs
     local exifdat="exif.dat"        # DSLR RAW images
     local fitsdat="rawfiles.dat"    # all FITS raw images (CCD, DSLR, bayered CMOS)
     
     msg="# Collecting image information ..."
-    test "$AO_SKIP" && skippat="$AO_SKIP" &&
+    if [ "$AO_SKIP" ]
+    then
         echo "# using expert option: AO_SKIP=$AO_SKIP"
+        skipargs=""
+        for s in ${AO_SKIP//,/ }
+        do
+            skipargs="$skipargs -not -path \"$AI_RAWDIR/$s\"\*"
+        done
+    fi
     
-    extlist=$(cd $AI_RAWDIR/ && find * -type f -not -path "$skippat"\* | sed -e 's,.*\.,,' | sort -u | \
-            grep -iwE "pef|cr2|nef|raf")
     if ! match proc "$SKIPPARTS"
     then
         echo $msg
@@ -504,11 +514,20 @@ _imageinfo () {
         # note: use AI_TZOFF=1 if DSLR camera time is MEZ instead of UT
         #   DSLR camera exif time is exposure end time + 30s
         infofile=$exifdat
+        extlist=$(eval find $AI_RAWDIR/ -type f $skipargs | sed -e 's,.*\.,,' | sort -u | \
+            grep -iwE "pef|cr2|nef|raf")
+        extargs="\( -iname \"*.pef\""
+        for s in cr2 nef raf
+        do
+            extargs="$extargs -or -iname \"*.$s\""
+        done
+        extargs="$extargs \)"
         test "$extlist" && for ext in $extlist
         do
             echo "# scanning $ext files ..."
-            img_info $(find $AI_RAWDIR/ -type f -not -path "$AI_RAWDIR/$skippat"\* -name "*.$ext" \
-                -not -path "$AI_RAWDIR/unused/*") | sort -n -k 2,2 >> $infofile
+            flist=$(eval find $AI_RAWDIR/ -type f $extargs $skipargs \
+                -not -path "$AI_RAWDIR/unused/*")
+            img_info $flist | sort -n -k 2,2 >> $infofile
             test $? -ne 0 && return 255
         done
         test -s $infofile && 
@@ -517,6 +536,12 @@ _imageinfo () {
         
         # scanning FITS images ...
         infofile=$fitsdat
+        extargs="\( -iname \"*.fit\""
+        for s in fits fts fit.gz fits.gz fts.gz fit.zip fits.zip fts.zip
+        do
+            extargs="$extargs -or -iname \"*.$s\""
+        done
+        extargs="$extargs \)"
         # FITS images from itelescope.net
         if grep -iq iTelescope.Net $AI_RAWDIR/[2T]*{txt,log} 2>/dev/null
         then
@@ -534,27 +559,18 @@ _imageinfo () {
                 test $tel == "jbl08" && tel=T68
                 test $tel == "T2" && tel=T20
                 echo "# scanning fits files for $tel ..."
-                flist=$(find $AI_RAWDIR/ -type f -not -path "$AI_RAWDIR/$skippat"\* \( -name "*fit.zip" -or -name "*fits" \) \
-                    -not -name "calib*" \
+                flist=$(eval find $AI_RAWDIR/ -type f $extargs $skipargs \
                     -not -path "$AI_RAWDIR/unused/*" | grep -iw $tel)
                 # TODO: check JD in first file, if it is not plausible then use time
                 # info from log file by providing -l option
-                map_rawfiles -x $flist >> $infofile
+                test "$flist" && map_rawfiles -x $flist >> $infofile
                 test $? -ne 0 && return 255
             done
         else
             # scanning other FITS images
-            test "$AI_DEBUG" && echo find $AI_RAWDIR/ -type f -not -path "$AI_RAWDIR/$skippat"\* -name "*.fts" >&2
-            flist=$(find $AI_RAWDIR/ -type f \( \
-                   -name "*.fit"  -o -name "*.FIT"  \
-                -o -name "*.fits" -o -name "*.FITS" \
-                -o -name "*.fts"  -o -name "*.FTS"  \
-                -o -name "*.fit.gz"  -o -name "*.fit.zip" \
-                -o -name "*.fits.gz" -o -name "*.fits.zip" \
-                -o -name "*.fts.gz"  -o -name "*.fts.zip" \) \
-                -not -path "$AI_RAWDIR/unused/*" \
-                -not -path "$AI_RAWDIR/$skippat"\*
-                )
+            test "$AI_DEBUG" && echo find $AI_RAWDIR/ -type f $extargs $skipargs >&2
+            flist=$(eval find $AI_RAWDIR/ -type f $extargs $skipargs \
+                -not -path "$AI_RAWDIR/unused/*")
             if [ "$flist" ]
             then
                 echo "# scanning fits files ..."
@@ -810,7 +826,7 @@ EOF
     do
         test -f n${set}.sd.pgm && continue
         nimg=$(AIsetinfo $set | awk '{print $9}')
-        test $nimg -lt 12 && continue
+        test $nimg -lt 9 && continue
         echo "# estimate dark noise in $set, nimg=$nimg"
         grep -v "^#" set.dat | awk -v s=$set '{
             if ($2==s) printf("%s n%s\n", $1, substr($0,7))}' > $AI_TMPDIR/x.nset.dat
@@ -2615,7 +2631,7 @@ _usercmd () {
         fi
     done
     
-    echo "$msg"
+    test -z "$quiet" && echo "$msg"
     test "$AI_DEBUG" && echo "nargs=$#"
     $usercmd "$@"
     return $?
@@ -2715,7 +2731,7 @@ do
         o)  OVERWRITE=1;;
         x)  SKIPPARTS="$OPTARG";;
         c)  usercmd="$OPTARG";;
-        q)  quiet=1;;
+        q)  test -z "$AI_DEBUG" && quiet=1;;
         h)  longhelp; echo; task="help";;
         \?) shorthelp; exit -1;;
     esac
@@ -2842,7 +2858,7 @@ then
     then
         error "raw image directory $AI_RAWDIR is missing."
     else
-        echo "WARNING: raw image directory $AI_RAWDIR is missing."
+        test ! "$quiet" && echo "WARNING: raw image directory $AI_RAWDIR is missing."
     fi
 fi
 
@@ -2858,7 +2874,7 @@ do
 done
 
 airfun=$(which airfun.sh)
-echo "# airfun=$airfun"
+test -z "$quiet" && echo "# airfun=$airfun"
 if [ -z "$airfun" ]
 then
     error "missing function definition file airfun.sh
@@ -2947,9 +2963,9 @@ _cleanup () {
 trap _cleanup EXIT
 
 
-echo "# Running task $task ($(date +'%H:%M')) ..."
+test -z "$quiet" && echo "# Running task $task ($(date +'%H:%M')) ..."
 _$task "$@"
 errcode=$?
 test -z "$errcode" && error "Missing return code from task."
-test "$errcode" == "0" && echo "# task finished at $(date +'%H:%M')"
+test "$errcode" == "0" && test -z "$quiet" && echo "# task finished at $(date +'%H:%M')"
 exit $errcode
