pre-release 3.0 (airfun version 4.0, airtools-cli 1.0a2, new airtools-gui)

diff --git a/airtools b/airtools
--- a/airtools
+++ b/airtools
@@ -6,31 +6,77 @@
 #   a wrapper around airtools-gui.jar
 #
 ########################################################################
-VERSION="0.1"
-VINFO="T. Lehmann, Nov. 2018"
+VERSION="0.2"
+VINFO="T. Lehmann, Mar. 2019"
 PINFO="\
     options:
-      h          show this help text
-      args       program arguments passed over to java program
+      h         show this help text
+      l         prefer java program from users bin directory
+      args      program arguments passed over to java program
 "
 CHANGELOG="
+    0.2  - 16 Mar 2019
+        * added option -l to prefer java program from users bin directory
+        * improved error checking and messages
+
     0.1  - 10 Nov 2018
         * initial version
 "
 
 
-test "$1" == "-h" &&
-    echo $(basename $0)"   $VERSION   $VINFO" >&2 &&
-    printf "$PINFO" &&
-    exit 1
-
-# find program jar file
+#--------------------
+#   user definitions
+#--------------------
 jar=airtools-gui.jar
 datadir=/usr/share/airtools
-prog=$datadir/$jar
-test -e $prog || prog=$HOME/bin/$jar
-test -e $prog || prog=$HOME/bin/home/$jar
 
+
+#--------------------
+#   get options
+#--------------------
+cmdline="$(basename $0) $@"  # preserve command line
+prefer_local_bin=""
+testonly=""
+showhelp=""
+for i in $(seq 1 3)
+do
+    (test "$1" == "-h" || test "$1" == "--help") && showhelp=1 && shift 1
+    test "$1" == "-l" && prefer_local_bin=1 && shift 1
+    test "$1" == "-t" && testonly=1 && shift 1
+done
+
+
+#--------------------
+#   checkings
+#--------------------
+test "$showhelp" &&
+    echo $(basename $0)"   $VERSION   $VINFO" >&2 &&
+    printf "$PINFO" >&2 &&
+    exit -1
+
+# find program jar file
+prog=""
+test -e "$datadir/$jar" && prog="$datadir/$jar"
+if [ "$prefer_local_bin" ]
+then
+    test -e $HOME/bin/$jar      && prog=$HOME/bin/$jar
+    test -e $HOME/bin/home/$jar && prog=$HOME/bin/home/$jar
+fi
+if [ -z "$prog" ]
+then
+    msg="Unable to find $jar"
+    type -p yad >/dev/null &&
+        yad --title "Error" --window-icon=none --image=gtk-dialog-error --no-buttons --text "\n  $msg" && exit 1
+    type -p zenity >/dev/null &&
+        zenity --error --text "\n  $msg" && exit 1
+    notify-send -u critical -i gtk-dialog-error "$msg"
+    exit 1
+fi
+
+
+#--------------------
+#   start
+#--------------------
 # set Java 8 runtime
 # (currently there are problems using Java 11 which is the default java
 # on Ubuntu 18.04)
@@ -41,5 +87,9 @@ test -z "$JAVA_HOME" &&
     exit 255
 
 # start java program
-$JAVA_HOME/bin/java -jar $prog "$@"
-exit 0
+if [ "$testonly" ]
+then
+    echo $JAVA_HOME/bin/java -jar $prog "$@"
+else
+    $JAVA_HOME/bin/java -jar $prog "$@"
+fi
